# Generated by Django 6.0.2 on 2026-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visit_number', 'Visit model number seq')], max_length=100, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
            ],
        ),
    ]
