# Generated by Django 6.0.2 on 2026-02-21 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'duties',
            },
        ),
        migrations.CreateModel(
            name='DutyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done')], default='not_done', max_length=10)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_visits.duty')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=10, unique=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caregiver_visits', to=settings.AUTH_USER_MODEL)),
                ('duties', models.ManyToManyField(blank=True, through='patient_visits.DutyResult', to='patient_visits.duty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dutyresult',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_results', to='patient_visits.visit'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyresult',
            unique_together={('visit', 'duty')},
        ),
    ]
