# Generated by Django 6.0.2 on 2026-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.AlterModelManagers(
            name='visit',
            managers=[
            ],
        ),
    ]
