# Generated by Django 6.0.2 on 2026-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_visits', '0002_controlsequence_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlSequence',
        ),
    ]
